import React,{useEffect,useMemo,useState} from 'react';
import {AlertTriangle,Archive,ArrowDownUp,Bell,CalendarDays,Check,ChevronDown,ChevronLeft,ChevronRight,Clock3,Grid2X2,Heart,LayoutDashboard,Leaf,List,MapPin,Moon,Package,Plus,RotateCcw,Search,ShieldCheck,Sun,Trash2,X,Pencil,Filter,Sprout,ScanLine} from 'lucide-react';
import OCRProductForm from './ProductForm.jsx';
import Scanner from './Scanner.jsx';
import { useTranslation } from './i18n.jsx';
import logo from '../logo.png';

const demoProductIds=new Set(['1','2','3','4','5','6','7','8','9']);
const getDays=date=>Math.ceil((new Date(date+'T23:59:59')-new Date(new Date().toDateString()))/86400000);
const status=date=>getDays(date)<0?'Expired':getDays(date)<=3?'Expiring soon':'Fresh';
const getGreeting=()=>{const hour=new Date().getHours();if(hour>=5&&hour<12)return {label:'Good morning',emoji:'☀️'};if(hour>=12&&hour<17)return {label:'Good afternoon',emoji:'🌤️'};if(hour>=17&&hour<21)return {label:'Good evening',emoji:'🌇'};return {label:'Good night',emoji:'🌙'}};
const fmt=(date,language='en')=>new Date(date+'T12:00:00').toLocaleDateString(language==='hi'?'hi-IN':'en-IN',{month:'short',day:'numeric'});
const safeRead=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}};
const withoutDemoProducts=value=>Array.isArray(value)?value.filter(product=>!demoProductIds.has(String(product?.id))):[];
const persist=(key,value)=>{try{localStorage.setItem(key,JSON.stringify(value));return true}catch{return false}};
function App(){
 const {language,setLanguage,t}=useTranslation();
 const [items,setItems]=useState(()=>withoutDemoProducts(safeRead('expicare.products',[])));
 const [bin,setBin]=useState(()=>withoutDemoProducts(safeRead('expicare.bin',[])));
 const [theme,setTheme]=useState(()=>localStorage.getItem('expicare.theme')||'light');
 const [page,setPage]=useState('Dashboard'),[query,setQuery]=useState(''),[category,setCategory]=useState('All items'),[sort,setSort]=useState('expiry'),[modal,setModal]=useState(null),[selected,setSelected]=useState(null),[toast,setToast]=useState(''),[mobile,setMobile]=useState(false),[loading,setLoading]=useState(true);
 useEffect(()=>{if(!persist('expicare.products',items))notify(t('Browser storage is full. Remove a photo or product to save changes.'))},[items]);
 useEffect(()=>{if(!persist('expicare.bin',bin))notify(t('Browser storage is full. Empty the recycle bin to save changes.'))},[bin]);
 useEffect(()=>{try{localStorage.setItem('expicare.theme',theme)}catch{}document.documentElement.dataset.theme=theme},[theme]);
 useEffect(()=>{const timer=setTimeout(()=>setLoading(false),1200);return()=>clearTimeout(timer)},[]);
 const soon=useMemo(()=>items.filter(p=>p.reminder&&getDays(p.expiry)<=3),[items]);
 const upcoming=items.filter(p=>getDays(p.expiry)>=0&&getDays(p.expiry)<=7).sort((a,b)=>a.expiry.localeCompare(b.expiry));
 const notify=m=>{setToast(m);setTimeout(()=>setToast(''),2400)};
 const nav=['Dashboard','Scan product','Products','Categories','Reminders','Recycle bin'];
 const go=p=>{setPage(p);setSelected(null);setMobile(false)};
 const remove=p=>{setBin(b=>[{...p,deletedAt:new Date().toISOString()},...b]);setItems(a=>a.filter(x=>x.id!==p.id));setSelected(null);notify(t('Moved to recycle bin'))};
 const restore=p=>{setItems(a=>[p,...a]);setBin(b=>b.filter(x=>x.id!==p.id));notify(t('Product restored'))};
 const save=p=>{if(modal?.id){setItems(a=>a.map(x=>x.id===p.id?p:x));setSelected(p);notify(t('Changes saved'))}else{setItems(a=>[p,...a]);notify(t('Product added'))}setModal(null)};
 if(loading)return <div className="splash"><img src={logo} alt="ExpiCare — Smart Expiry Management System"/><div className="loader-track"><i/></div><span>{t('Taking care of the little things...')}</span></div>;
 return <div className="shell">
  <aside className={`sidebar ${mobile?'open':''}`}>
   <div className="side-brand"><img src={logo} alt="ExpiCare — Smart Expiry Management System"/><button className="icon mobile-close" onClick={()=>setMobile(false)} aria-label={t('Close navigation')}><X/></button></div>
   <div className="workspace"><div className="avatar">E</div><div><b>{t('My home')}</b><small>{t('Personal space')}</small></div><ChevronDown size={16}/></div>
   <div className="nav-caption">{t('WORKSPACE')}</div>
   <nav>{nav.map((n,i)=>{const I=[LayoutDashboard,ScanLine,Package,Grid2X2,Bell,Archive][i];return <button key={n} className={`nav-link ${page===n&&!selected?'active':''}`} onClick={()=>go(n)}><I size={18}/><span>{t(n)}</span>{n==='Reminders'&&soon.length>0&&<i className="nav-badge">{soon.length}</i>}</button>})}</nav>
   <div className="sidebar-note"><div className="note-icon"><Sprout size={18}/></div><b>{t('A little care goes a long way.')}</b><p>{t('Track what you have. Waste a little less.')}</p><span>♻ &nbsp;{t('You’re making a difference')}</span></div>
   <div className="profile"><div className="avatar">E</div><div><b>ExpiCare</b><small>{t('Personal space')}</small></div><span className="profile-settings">•••</span></div>
  </aside>
  <main>
   <header className="topbar"><button className="icon mobile-menu" onClick={()=>setMobile(true)} aria-label={t('Open navigation')}><List/></button><div className="crumb">{t('My home')} <ChevronRight size={15}/><b>{selected?selected.name:t(page)}</b></div>
    <div className="top-tools"><span className="date-chip"><CalendarDays size={15}/>{new Date().toLocaleDateString(language==='hi'?'hi-IN':'en-IN',{weekday:'short',month:'short',day:'numeric'})}</span>
     <div className="language-toggle" role="group" aria-label={t('Choose language')}><button type="button" className={language==='en'?'selected':''} aria-pressed={language==='en'} onClick={()=>setLanguage('en')}>EN</button><button type="button" className={language==='hi'?'selected':''} aria-pressed={language==='hi'} onClick={()=>setLanguage('hi')}>हिंदी</button></div>
     <button className="icon" title={t('Toggle light/dark mode')} aria-label={t('Toggle light/dark mode')} onClick={()=>setTheme(theme==='light'?'dark':'light')}>{theme==='light'?<Moon/>:<Sun/>}</button><button className="icon bell-button" title={t('Reminders')} aria-label={t('Reminders')} onClick={()=>go('Reminders')}><Bell/>{soon.length>0&&<i/>}</button><div className="avatar">E</div></div>
   </header>
   <div className="content">{selected?<Details p={selected} back={()=>setSelected(null)} edit={()=>setModal(selected)} remove={()=>remove(selected)}/>:page==='Scan product'?<Scanner onBack={()=>go('Products')} onSave={product=>{setItems(current=>[product,...current]);go('Products');notify(t('Product added'))}}/>:page==='Dashboard'?<Dashboard items={items} upcoming={upcoming} soon={soon.length} go={go} add={()=>setModal({})} open={setSelected}/>:page==='Products'?<Products items={items} query={query} setQuery={setQuery} category={category} setCategory={setCategory} sort={sort} setSort={setSort} add={()=>setModal({})} open={setSelected}/>:page==='Categories'?<Categories items={items} choose={c=>{setCategory(c);go('Products')}}/>:page==='Reminders'?<Reminders items={items} soon={soon} open={setSelected}/>:<Recycle bin={bin} restore={restore} clear={()=>{setBin([]);notify(t('Recycle bin emptied'))}}/>}</div>
   <footer><span>{t('Made with')} <Heart size={12} fill="currentColor"/> {t('for a little less waste')}</span><span>ExpiCare · {t('Smart expiry management')}</span></footer>
  </main>
  {mobile&&<div className="scrim" onClick={()=>setMobile(false)}/>} {modal&&<OCRProductForm product={modal.id?modal:null} close={()=>setModal(null)} save={save}/>} {toast&&<div className="toast"><Check size={16}/>{toast}</div>}
 </div>
}
function PageTitle({eyebrow,title,desc,action}){return <div className="page-title"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{desc}</p></div>{action}</div>}
function Primary({children,onClick}){return <button className="primary" onClick={onClick}><Plus size={17}/>{children}</button>}
function Pill({date}){const {t}=useTranslation();let s=status(date);return <span className={'pill '+s.toLowerCase().replace(' ','-')}><i/>{t(s)}</span>}
function ProductRow({p,open}){const {language,t}=useTranslation();let d=getDays(p.expiry);const remaining=d<0?`${Math.abs(d)} ${t('days ago')}`:d===0?t('Today'):`${d} ${t('days left')}`;return <button className="product-row" onClick={open}><div className="product-emoji">{p.photo?<img src={p.photo} alt={p.name}/>:p.emoji||'📦'}</div><div className="product-info"><b>{p.name}</b><small>{p.brand||t(p.category)}</small><span><MapPin size={12}/>{p.location||t('No location')} <i>·</i> {p.quantity||`1 ${t('item')}`}</span></div><div className="product-expiry"><Pill date={p.expiry}/><small>{remaining}</small></div><ChevronRight className="row-chevron" size={17}/></button>}
function Empty({title,desc,action}){return <div className="empty"><div className="empty-icon"><Check size={21}/></div><b>{title}</b><p>{desc}</p>{action}</div>}
function Stat({icon:Icon,label,value,note,color}){return <div className="stat"><div className={'stat-icon '+color}><Icon size={17}/></div><div><span>{label}</span><strong>{value}<small>{note}</small></strong></div><i>↗</i></div>}
function Dashboard({items,upcoming,soon,go,add,open}){
 const {language,t}=useTranslation();
 const [greeting,setGreeting]=useState(getGreeting);
 useEffect(()=>{const timer=setInterval(()=>setGreeting(getGreeting()),60_000);return()=>clearInterval(timer)},[]);
 const fresh=items.filter(p=>status(p.expiry)==='Fresh').length;
 const today=new Date().toLocaleDateString(language==='hi'?'hi-IN':'en-IN',{weekday:'long',month:'long',day:'numeric'});
 const reminderHeading=soon?(language==='hi'?`${soon} रिमाइंडर आपके लिए`:`${soon} gentle reminder${soon===1?'':'s'} for you`):t('Your reminders are all set');
 return <>
  <PageTitle eyebrow={today.toLocaleUpperCase(language==='hi'?'hi-IN':'en-IN')} title={`${t(greeting.label)} ${greeting.emoji}`} desc={t('Here’s a fresh look at everything you’re taking care of.')} action={<Primary onClick={add}>{t('Add product')}</Primary>}/>
  <section className="hero"><div className="hero-copy"><div className="hero-kicker"><Leaf size={14}/> {t('YOUR HOME, AT A GLANCE')}</div><h2>{t('A little more mindful,')}<br/>{t('a little less waste.')}</h2><p>{t('You’re doing great. Keep an eye on what needs a little love this week.')}</p><button onClick={()=>go('Products')}>{t('Explore your products')} <ChevronRight size={15}/></button></div><div className="hero-art"><div className="glow"/><div className="plant">🌱</div><div className="hero-count"><b>{items.length}</b><span>{t('things in')}<br/>{t('your care')}</span></div></div></section>
  <section className="stats"><Stat icon={Package} label={t('Total products')} value={items.length} note={t('in your home')} color="mint"/><Stat icon={Clock3} label={t('Expiring soon')} value={items.filter(p=>getDays(p.expiry)>=0&&getDays(p.expiry)<=3).length} note={t('in the next 3 days')} color="peach"/><Stat icon={AlertTriangle} label={t('Already expired')} value={items.filter(p=>getDays(p.expiry)<0).length} note={t('worth checking')} color="pink"/><Stat icon={ShieldCheck} label={t('Up to date')} value={fresh} note={t('looking good')} color="blue"/></section>
  <div className="dashboard-panels"><section className="panel"><div className="panel-heading"><div><h3>{t('Coming up soon')} <span className="count">{upcoming.length}</span></h3><p>{t('Let’s make sure nothing goes to waste.')}</p></div><button className="text-button" onClick={()=>go('Products')}>{t('View all')} <ChevronRight size={15}/></button></div>{upcoming.length?<div className="compact-list">{upcoming.slice(0,4).map(p=><button className="compact-row" key={p.id} onClick={()=>open(p)}><span className="compact-emoji">{p.emoji}</span><span className="compact-name"><b>{p.name}</b><small>{p.location||t('No location')}</small></span><span className="compact-date"><b>{fmt(p.expiry,language)}</b><small>{getDays(p.expiry)===0?t('Today'):`${getDays(p.expiry)} ${t('days')}`}</small></span><ChevronRight size={15}/></button>)}</div>:<Empty title={t('All caught up')} desc={t('Nothing is expiring in the next week.')}/>}</section>
   <section className="panel mindful"><div className="panel-heading"><div><h3>{t('Your mindful moment')}</h3><p>{t('Small steps make a real difference.')}</p></div><span className="leaf-chip"><Leaf size={18}/></span></div><div className="food-art"><span>🥑</span><span>🥬</span><span>🍋</span><span>🌿</span></div><div className="mindful-foot"><div><b>{fresh} {t('products are looking good')}</b><p>{t('That’s a lovely start to the week.')}</p></div><div className="ring"><span>{items.length?Math.round(fresh/items.length*100):0}%</span></div></div></section>
  </div>
  <div className="reminder-strip"><div><span className="strip-icon"><Bell size={18}/></span><div><b>{reminderHeading}</b><p>{t(soon?'A few things could use your attention soon.':'We’ll let you know when something needs attention.')}</p></div></div><button className="text-button" onClick={()=>go('Reminders')}>{t('See reminders')} <ChevronRight size={15}/></button></div>
 </>;
}
function Products({items,query,setQuery,category,setCategory,sort,setSort,add,open}){
 const {t}=useTranslation();
 let cats=['All items',...new Set(items.map(p=>p.category))];
 let list=items.filter(p=>(category==='All items'||p.category===category)&&(p.name+' '+p.brand+' '+p.category+' '+p.location).toLowerCase().includes(query.toLowerCase()));
 list=[...list].sort((a,b)=>sort==='name'?a.name.localeCompare(b.name):a.expiry.localeCompare(b.expiry));
 return <><PageTitle eyebrow={t('YOUR INVENTORY')} title={t('Products')} desc={t('Everything you have, all in one thoughtful place.')} action={<Primary onClick={add}>{t('Add product')}</Primary>}/>
  <div className="toolbar"><label className="search"><Search size={17}/><input placeholder={t('Search your products...')} value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button aria-label={t('Clear search')} onClick={()=>setQuery('')}><X size={15}/></button>}</label>
   <label className="select"><Filter size={15}/><select aria-label={t('Category')} value={category} onChange={e=>setCategory(e.target.value)}>{cats.map(c=><option key={c} value={c}>{t(c)}</option>)}</select><ChevronDown size={14}/></label>
   <label className="select"><ArrowDownUp size={15}/><select aria-label={t('Sort products')} value={sort} onChange={e=>setSort(e.target.value)}><option value="expiry">{t('Expiry date')}</option><option value="name">{t('Name A–Z')}</option></select><ChevronDown size={14}/></label>
  </div>
  <div className="list-caption">{list.length} {t(list.length===1?'product':'products')}{category!=='All items'?` ${t('in')} ${t(category)}`:''}<span><i className="green-dot"/> {t('Fresh')} &nbsp; <i className="orange-dot"/> {t('Expiring soon')}</span></div>
  {list.length?<div className="rows">{list.map(p=><ProductRow key={p.id} p={p} open={()=>open(p)}/>)}</div>:<Empty title={t(query?'No matches found':'No products yet')} desc={t(query?'Try another name or category.':'Add something you would like to keep an eye on.')} action={!query&&<Primary onClick={add}>{t('Add product')}</Primary>}/>}
 </>;
}
function Categories({items,choose}){const {t}=useTranslation();const cats=[...new Set(items.map(p=>p.category))];const emoji={Produce:'🥑',Dairy:'🥛',Healthcare:'💊',Bakery:'🥐',Pantry:'🫙','Dairy alternatives':'🧃'};return <><PageTitle eyebrow={t('A PLACE FOR EVERYTHING')} title={t('Categories')} desc={t('A little order makes mindful living feel effortless.')}/><div className="category-grid">{cats.map((c,i)=><button className="category-card" key={c} onClick={()=>choose(c)}><span className={'category-emoji cat-'+i%5}>{emoji[c]||'📦'}</span><span className="category-name"><b>{t(c)}</b><small>{items.filter(p=>p.category===c).length} {t('products')}</small></span><span className="cat-preview">{items.filter(p=>p.category===c).slice(0,3).map(p=><i key={p.id}>{p.emoji}</i>)}</span><ChevronRight size={16}/></button>)}</div></>}
function Reminders({items,soon,open}){const {t}=useTranslation();const later=items.filter(p=>p.reminder&&getDays(p.expiry)>3).sort((a,b)=>a.expiry.localeCompare(b.expiry));return <><PageTitle eyebrow={t('A FRIENDLY NUDGE')} title={t('Reminders')} desc={t('A heads-up when something could use your attention.')}/><div className="reminder-intro"><span><Bell size={20}/></span><div><b>{t('You’re in the loop')}</b><p>{t('Reminders are shown for products expiring within 3 days. Adjust them on each product.')}</p></div><small>{soon.length} {t('active')}</small></div><h4 className="section-label">{t('NEEDS A LITTLE LOVE')}</h4>{soon.length?<div className="rows">{soon.map(p=><ProductRow key={p.id} p={p} open={()=>open(p)}/>)}</div>:<Empty title={t('A quiet day ahead')} desc={t('No products need a reminder right now.')}/>}<h4 className="section-label">{t('UPCOMING REMINDERS')}</h4>{later.length?<div className="rows">{later.map(p=><ProductRow key={p.id} p={p} open={()=>open(p)}/>)}</div>:<p className="muted">{t('No more reminders scheduled.')}</p>}</>}
function Recycle({bin,restore,clear}){const {language,t}=useTranslation();return <><PageTitle eyebrow={t('A SECOND CHANCE')} title={t('Recycle bin')} desc={t('Deleted products stay here until you restore or clear them.')} action={bin.length>0&&<button className="secondary danger" onClick={clear}><Trash2 size={15}/> {t('Empty bin')}</button>}/>{bin.length?<div className="rows">{bin.map(p=><div className="trash-row" key={p.id}><span className="compact-emoji">{p.emoji}</span><span className="compact-name"><b>{p.name}</b><small>{t('Deleted')} {new Date(p.deletedAt).toLocaleDateString(language==='hi'?'hi-IN':'en-IN',{month:'short',day:'numeric'})}</small></span><button className="secondary" onClick={()=>restore(p)}><RotateCcw size={15}/> {t('Restore')}</button></div>)}</div>:<Empty title={t('Nothing in the bin')} desc={t('Products you delete will find a home here for a while.')}/>}</>}
function Details({p,back,edit,remove}){const {language,t}=useTranslation();return <><button className="back" onClick={back}><ChevronLeft size={17}/> {t('Back to products')}</button><div className="detail-heading"><div><div className="eyebrow">{t('PRODUCT DETAILS')}</div><h1>{p.name}</h1><p>{p.brand||t(p.category)}</p></div><div className="detail-buttons"><button className="secondary" onClick={edit}><Pencil size={15}/> {t('Edit')}</button><button className="icon danger-icon" title={t('Delete product')} aria-label={t('Delete product')} onClick={remove}><Trash2 size={17}/></button></div></div><div className="detail-grid"><section className="panel detail-panel"><div className="detail-illustration">{p.photo?<img src={p.photo} alt={p.name}/>:p.emoji||'📦'}</div><div className="detail-fields"><h3>{t('About this product')}</h3><Info label={t('Category')} value={t(p.category)}/><Info label={t('Quantity')} value={p.quantity||'—'}/>{p.barcode&&<Info label={t('Barcode')} value={p.barcode}/>}<Info label={t('Storage location')} value={p.location||'—'}/><Info label={t('Date added')} value={fmt(p.added||p.expiry,language)}/></div></section><section className="panel expiry-panel"><CalendarDays size={20}/><div className="eyebrow">{t('BEST BEFORE')}</div><h2>{new Date(p.expiry+'T12:00:00').toLocaleDateString(language==='hi'?'hi-IN':'en-IN',{month:'long',day:'numeric',year:'numeric'})}</h2><Pill date={p.expiry}/><hr/><div className="reminder-pref"><Bell size={16}/><span><b>{t('Gentle reminder')}</b><small>{p.reminder?t('You’ll get a heads-up'):t('Reminders are off')}</small></span><i className={p.reminder?'toggle on':'toggle'}/></div></section></div><div className="detail-tip"><Leaf size={17}/><span><b>{t('A little tip')}</b> &nbsp;{t('When in doubt, check the product before enjoying.')}</span></div></>}
function Info({label,value}){return <div className="info-row"><span>{label}</span><b>{value}</b></div>}
export default App;
